env:
  global:
    - CC_TEST_REPORTER_ID=ef9987fd97eefaf4017a8b88e063e9376b408e93b170ad4610c8fce4370f4be2

language: ruby
git:
  depth: 1

rvm:
- 3.0.0

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
- bin/rspec spec

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

deploy:
  provider: rubygems
  api_key:
    secure: YLM/BiQPu0GMgns2tUeE1qO58JmzRVfo20ebgG6XNBqmptzPI3ReqEs/bYaUSdygYiK81pVhy69dWj3bjKjWV6C7EBr/w6tOE+qM6PUKEvd8rlcviXXUOgFfMCLLqREYi21zr+I0Z1Gj8mCRklBV2DFF+f6TTIcSh/afYVVWv8rktpMgivijB9Cexek5gP/8zhg8AaKAnGBzrmKzxraKZA7s97e5iWvZBMLtrDyqSe8mfkviKeOE6B1sKb8YdYLh9fSSpNewOEzKTtgS2AWmoCdP6IiUk+dhORTHu0s13Rz+nD2ZOYfkYIXt6iMNYlFHB30Nm1/4iusCrStIphDXlLqCD6DfBX4gRmBgRHsceCHoHggWqOCbgz28MI1vtkFsnoLz7/fJBlpPy/g+7VC6SnSt5fux35W4u26QcvMwmD3MkwJmjjktsi+GlIF9D+oDtb79VTUM1hzT2kkByWATZJnUK9M3CxxzGe4CqXpeFpVW5d0K84aMd0jpAuKFZf87jOVtQ80Jtl/ANFpHP/LO8P/SUil4OZh2eKmIADZg/z6itytkK/lcU5uEIpHIctP7q1oNqX27tLTPdoY1ht7gJ/x9IUL7lqTDsY7nRW7PrO3sNwzT1NCDIeAC2K/k7WCdrEKk3oj4C3Eqykho6X7tx+lfd2eTN6bzAcekCSseezE=
  gem: coltrane
  on:
    repo: pedrozath/coltrane
notifications:
  slack:
    secure: Z1DrNRL47BvEB/PWyb+EsVlAwVsGapytLGCiyQeTlNBTK7iCfP3N57fkVZDyaMYWJ7oweCk16aTBxljnP6SPNaqQhKWilDXiwnX9s3uWxz06ONgg8TE46hGyplD5fmt/liIxQ/XeJoCA8C6qWJRAc94Y0b42yK23eFbCU3632ISt1wVwipOcuAyCD0TTjQUHRjWT4Zbg6gqytG+U3rsx2+wGUDbu2Nu5r6C90uU0vbmHyhcmf2S7V7is7Kpc24aDhPhBBrP44uWXLEXh8Hgthca95jVm2CoL2GVK+f6W/mAkQugkg0Rz//d8+9M5SJcHQiUBwNIXxfgEQKkVFSuiMcySdG0RFBh9dyPPem3AUWEO9HwNlF+juMkwP+Wavj9eoN3cWNeVJrT00mXaTzmPdxFKxvRKp/NSJQIKI7dzg74oggyzu5BSmTlth2YGgNzEhKbAjOGL+B2ClE5KeR4ZIUsEH7Z/KAoHH4EPERYqec+aSsbLuoAAQiuRIqul+MyZiz0ox/kA1hFVndbDg7avxqZUzBSBZ7f9nMzKxQeUGSJYS3f5XWYpIDCxEiub5LiLMkltaM2AGAzZfFhLYEC96J/HoyF7xxHZNWbEJiv+bLuQGcD8BUCTNfRZM15nQbaKNBpyx/lC0h4kRAGnaGAnfGYCuKHjHPWsSAc8jcmW3Bw=
